# Generated by Django 6.0.5 on 2026-05-28 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.TextField(db_column='City_Name')),
            ],
            options={
                'db_table': 'Cities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pharmacies',
            fields=[
                ('pharmacy_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.TextField(blank=True, db_column='Branch_Name', null=True)),
                ('city', models.ForeignKey(db_column='City_ID', on_delete=django.db.models.deletion.CASCADE, to='pharmacy.cities')),
            ],
            options={
                'db_table': 'Pharmacies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(blank=True, db_column='First_Name', null=True)),
                ('last_name', models.TextField(blank=True, db_column='Last_Name', null=True)),
                ('email', models.EmailField(db_column='Email', max_length=254, unique=True)),
                ('password', models.TextField(db_column='Password')),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('city', models.ForeignKey(blank=True, db_column='City_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.cities')),
            ],
            options={
                'db_table': 'Users',
                'managed': True,
            },
        ),
    ]
