# Generated by Django 6.0.5 on 2026-05-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveIngredients',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(db_column='Ingredient_Name', max_length=100)),
            ],
            options={
                'db_table': 'Active_Ingredients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_column='Category_Name', max_length=100)),
            ],
            options={
                'db_table': 'Categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountCards',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount_percent', models.IntegerField(db_column='Discount_Percent')),
            ],
            options={
                'db_table': 'Discount_Cards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('price', models.FloatField(db_column='Price')),
            ],
            options={
                'db_table': 'Inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('manufacturer_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_column='Company_Name', max_length=150)),
                ('country', models.CharField(db_column='Country', max_length=100)),
            ],
            options={
                'db_table': 'Manufacturers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(db_column='Medicine_Name', max_length=150)),
            ],
            options={
                'db_table': 'Medicines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MLRecommendations',
            fields=[
                ('rec_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ML_Recommendations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='Quantity')),
            ],
            options={
                'db_table': 'Order_Items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(db_column='Order_Date')),
            ],
            options={
                'db_table': 'Orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(db_column='Doctor_Name', max_length=150)),
            ],
            options={
                'db_table': 'Prescriptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(db_column='Rating')),
            ],
            options={
                'db_table': 'Reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchLogs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('searched_word', models.CharField(db_column='Searched_Word', max_length=255)),
            ],
            options={
                'db_table': 'Search_Logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(db_column='Supplier_Name', max_length=150)),
            ],
            options={
                'db_table': 'Suppliers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSymptoms',
            fields=[
                ('symptom_id', models.AutoField(primary_key=True, serialize=False)),
                ('symptom_name', models.CharField(db_column='Symptom_Name', max_length=255)),
            ],
            options={
                'db_table': 'User_Symptoms',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cities',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pharmacies',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
